{ pkgs, lib, ... }:
let
  nixpkgs-vector = builtins.fetchGit {
    url = "https://github1.vg.vector.int/fbuehler/nixpkgs-vector.git";
    rev = "3a8fce1c2fd2f03eb5f62f2a896e80cbce5f3ffc";
  };
in
{
  imports = [
    "${nixpkgs-vector}/modules/vector/default.nix"
  ];

  snowfallorg.users.jan.home.config = {
    home.stateVersion = "24.11";
    programs.git.settings.user = {
      name = lib.mkForce "Lafferton, Jan";
      email = "jan.lafferton@vector.com";
    };
    programs.jujutsu.settings.user = {
      name = lib.mkForce "Lafferton, Jan";
      email = "jan.lafferton@vector.com";
    };
  };

  vector.proxy-settings.enable = true;

  systemd.services.nix-daemon.serviceConfig = {
    Environment = [
      "NIX_SSL_CERT_FILE=\"/etc/ssl/certs/ca-certificates.crt\""
      "SSL_CERT_FILE=\"/etc/ssl/certs/ca-certificates.crt\""
    ];
  };

  services.atticd = {
    enable = true;
    environmentFile = pkgs.writeText "atticd.env" ''
      ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64 = LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBbTNQNnFUYjk3b2VDRTdKdWNkUUxQbHdpS1NTSEJiQm9UTzhGS0x1TkVwVU10Z1BkCmJVSE9kMlJ5OGlzSVkvVGlETmhMeTBEankxRDVzeXozK25KNTJxVmhOZ2czaDM0c0dXbUtQdkd3eWsyRHExNnIKWkhEV2lpdHN1TlJjQThBanhWQ2hQamRtY2l2d1FINWlXVmpLdGlGTG8wakRGbjJWazM0WmlNT055TEZoaEZZegoxWUdwZXQralF1ODU2bU1BTGtGNTVhUlRoQlVucnVENEtEYVYwWWlxWmhhcUF4b2VCSlA3dzNSNS8yYjFPeU9uCkwwdGdoOGg1cXhxNmZpLzhoZFNyTDI3QkVVTGhaMWU2a3lDaGN3b3FyVzJISmJCVG1aVEpJaE5iMEtWOTN6K2kKOHUzQ0kzNFJZMlQ5bkhPalZxdlNKdElGOUxhejJ1dFRJd1N3eXBTcStrc2xJeEhUTVRUWkgramptM3FvWkF3ZApIUEV1Sjc4QnZTcDBTSTlEYUkyamJ6eHJLTDZCQWJHY1dneW1vUU1yWUZ4clhUNjBodEJvb2N4Ykd1aTJqRWYrCjRGZUswTTVDNGhoSlhaUU00K2pnYS9IZW80MTJHdnpzbjM0QWFva0NUQ1RPK3h0VGsxcUFXV01lZkphajJIemQKZjdSbzZFL0F1QS81enpsYUxSMWZMd0FKMTRlVDJBNDNqZkZoUWlQbDQ4T011Z2V0UmkvT3NPb0JaZVBCZm80RwovZjFKZ01saWRRZnJ3NTlrd2hRTnArNDY4TDVZdlh4M29Cb0k1M0xCbS9hejQwZWg3a1pRT0tsQjVXS09VYzNpClVWOUNwSWxxdXRSZm45cEFlb2owVTNxUXNaRTdVUkFVVjRqSi9VTHdhTVZJdzBtbENOMGxTckFZSStVQ0F3RUEKQVFLQ0FnRUFqUmZRUzZPeENMMlBUNGRrL1FXaml0OGUxazdrQ2tMWjkvSDlzY0hBd2p2c1JJdnZmc242dHB6QwpRNURSVmNBZko5OXRzN1pheXQvZE0wWStjTjlVUUNKWXdDem5FYUJ3TUVSOWlMSGZiMDY1a21Jamw4OWV1aHU5CjIyaExkOC85NTRwT1AyVVRJODlEaVpYc2VBSENRMXFuQnpYMGM4WmFhM3RKZTd0YVJlelJnTWFvMTBHUGJRbnMKYWNVdHdOSklpTE0vQ3pLQjV1RTRtbDV3ZmpkRTllQmdJTGF6YW90YThYYkxUTlM4SWhiMXY4NlZZTFMra1o5Zwo1dThrazRIRVprZm5jKzdIWjM1WGpXK3YxUGdKOFpzcHJ5MDVPL2oxZC9EMk9XcHVyRXA0bTVkcnM2Z2V6QTRSCmhEQldpNWpkaUwzOHlPVlpLSXBuWmV5dkVacWhSbU5Udk1CRVZwczZDU0hUVER4OVhwbVF2aTBGM2tPdmwybzkKK2hJS0hIWWQxSzRjYWFzbnVCNnhZZy9GTHRHVEhxQ3Vpd3JrZmJneGQ0Ri9PT2xwaHhiekI1UDZBS1ZBeDJNcQpid0M0ZHlGS3d4QnY5YWw0ZTY5OFhmTmw1VHNkMTNOQ3Nxc2FPMzA3TzZmemtadUpBaUUvK2d2QnNveFlORFZrCktOSmZXMjhYZ1BPUktITEJGckhqRFgrbzRaUGkyVjBockNtTjY0d1kxaUtrcXRRd05QZVNUQUt0blNzRXhRbVYKNklrVFEzYzkvdW44aEZBWHp4R3J6UUdtNjIvK1NOaWtYaG8zTitkb2FrYTJKYVA0M1NDUEVrWk1GRmFVYXdISgpSYkRxdHR3Y1B0Y0dHTnIrZktkVVlYVWlHMDd6NGpoc0ptNzIxV0FVSFJTODhhRG5MVVVDZ2dFQkFNWHhBeHdQClMraXdZRXBkK2ZQbnhLaWRQU0xtWUNSaVdZbTZseml5NXg2RS9tNDVTU1pYdFM0RTFJR2NGNjNwdXY4dm5UdU0KQklDSjdGSlJZenpSNG9Wd05NRXhQSnZ4aUpLMlYrVFZ6YmtzVVpmYzFwMFlKbUVFY0c3RDlWSHpRU0JVbFkrbwo1SXFiTUpweGQ1RWRHdFZXMmZ0TzY4VU9SU0FqOXM3UkhSVjVhV09oQ2k0dHJrQWljUWxGVk5OYUFweWVWVlExClV6NWFsMU5BSmhBdy8xZFZ5aFZZRU9wN1N0cWFoa2ZZeHk3Mk9VUG1KWTdyT250QVFpUE50dW0rRGZPS3EvYTIKb0NINWdvWFhTSW93ZitaR3FRZDcwWWJsbnJmSnhTam5ZamY3V1dFNVk0c082aVR6RjBrWXp2SlZCWFFFMEs4RgpReThlcFp0cVFGOVJYTXNDZ2dFQkFNa01teGkzNVBwRDhNVEMyVGFoYTllcHJGUUplbCtlZ3l4RjFaQXBxcjJzCkRqem1OSkRmakFpanFodUYwS1QrR1hXS25paEZ5VVFJcGUrMkF5VUpya1lwNTUyNkU0d2w2S1JxT2E1eldnaUkKS1pFTnY1Ukg1dTRINGVsQnlxZ2Z1Y2NjWHg1TC9SMkFYbDBwU1pyV1YydXdxZGdHVXZsVy9uek1hd09BcnJ6KwpKNWtjZWtpMXgwbCtIa3U0UUNWMWhJMVVsMWU4Si90UmFId0x5Y0ZNdkRxQm5PUXFzc04yT3BaK2UvcGFKRmgvCkl6dFVLd0lDaE9uSTVmUGRxdHVZaEFtazBWSUFEUFMwcGpOV2MxUk1neWRaVGl6WFRudU11MGtmQmVjWnlIS2kKdTJSUWZBZm5SN2tPZk13Z25mZnZuOGhJUll5VXkvcW5VS1hpRXVCWW5BOENnZ0VBY2pFSVNqZkk0d1JkaUltTwptVmNyN05wSldzanN6aEN1OXZYZUo2ZU9EZDFMcXVzQmVFMUJDTHRnblNVZnhBVUREQlM3OEk1bVNvRkhCSFpQCmVkYmJoMytqNzVBb0Z3N1FhMU1tZ2EyV2NTMVFKUHdTRTY3SzlVMUtUNXhjK2xvTFNFdUR2TTBDaTdQYjVqMXYKYlJnTlV1WTMrdk1jc1NINlh3QmdjZy9SWjRJVGVwWjgrUWNCYjU1dTk1bzN4WFkzNjRLc1YxZ3NIZHpGVUJIQgo0N1ZnbVZHMHMzdUt4cnM2QThNQmxKRksxNXpVaklkSlE1b1FzdW52UGhoL1hYbDNNdmpkSEFkZmVqb25RbTlnCk9kaWc4SWZ6RzQ0aTRsKzFvUEdWL0hNQUJxdktkSHhYSVBJSndpYzdWOEFvSTBWSlVCVTNEc0ZLY1BTTk5ZdW0KZDFiSTRRS0NBUUFMSFVaSnRJalZDUUo3YmlZaDdnU1BOSk1SUmtEY25sKzBCOXhKanZRZ2JpMlBVazZmbjZ3WApJaTBhUG1pTlpucXowOGp3Z3dNZ1hyWUZyWE01RGZMemNBZWM0WmVKRE9OeWkyaks2eGVVRnlydEdPeDVYd3cyCkpudG5zTHBxVnU2blFqdEQ2b0dBcXdNTWRXYmJSM1Fud09seXhzNjVlQVN6azMxckFTY256WWtVM3MwbnpkekoKaEU1YWMwSWdrQUdXNnBFL1NXaVFiU3l3aHRwTmRGZUhpSGpLNkUxZm50NllTVC9EVkU1a0VnczVrV3FiUHRabwpNakg4TEVud3Y5cTB5Y2JFbUxvZW9RbjdGcEZqbktNM2ZxbGlzemhrZmlBd1o2V2s0L2ovMVYwMHEzcGYyWHBPCmthMTJmMnNjTk1RSmgyMUkyMFQzZzE1aS9UOTc1WW9qQW9JQkFRQ3ZQVTRHK1hkWjBQNC9iWTBsRkxDMUd3Y3cKa1FPR1VsY0gzNmFPSmJ1Vk5HeEdGU21EVzcybHFTK1BxSk5pRnEyQUpGbjY1ZjJNcFFIWlcwQ2RjUkpENXM4VApwNElGeHgxRGNxMFVOcmVCdm9GVzFCdXVHYkRyQmthTTBWaTJ2NDhUOVM2ODM2V2hZR2psM2lodkJHd1JadzBkClE2d3FKYmQwMmpOUC9HbHpUU3N4cHF5aGU0cnMzTmcvcHZMcXRSVTZ6QTc3OVVBQkd1eXo5UXRERGZZRzAwS3UKZXNyS1RFTVFURkNlYTl1VTBVVFNTUVFrTmJ0Ti9nc0NVUWhZa2grZTFCZlVSbTZlS3lsbHFmTnRBTXBWUDAyYQp2Q3Rlb2J2RkhxUGxkYTJzZTEyS2lvdHp0YUltcnNxRXQvdXZDclVSZ3hkaUZtRlV6R3g5UEFwYlVaeVYKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    '';
  };
  environment.systemPackages = [ pkgs.attic-client ];

  wsl.enable = true;
  stylix.enable = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.05"; # Did you read the comment?
}
